version: 2

build:
  os: "ubuntu-21.10"
  tools:
    python: "3.9"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: doc/requirements.txt